/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Dao.AdicionaisDAO;
import Dao.AdicionalPedidoDAO;
import Classe.Adicional;
import Classe.AdicionalPedido;
import Regra.RegrasGerenciamento;
import Tela.JTableMap.AdicionalJtable;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maiara
 */
public class ConsultaAdicionais extends javax.swing.JFrame {

    /**
     * Creates new form cadastroProdutos
     */
    private int idPedido;
    private int idProduto;
    private boolean somenteVer;
    private List<Adicional> listaAdicionaisInseridos = new ArrayList<Adicional>();
    private List<Adicional> listaAdicionaisNaoInseridos = new ArrayList<Adicional>();

    public ConsultaAdicionais(int idPedido, int idProduto, boolean somenteVer) {
        initComponents();

        this.idPedido = idPedido;
        this.idProduto = idProduto;
        this.somenteVer = somenteVer;
        carregarTabelaAdicionaisInseridos();
        carregaTabela();
        carregaDetalhesTela();
    }

    public void carregaDetalhesTela() {
        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/dir.png")));
        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/esq.png")));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/sair.png")));
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Icone/bacon.png")).getImage());

        setDefaultCloseOperation(RealizarPedido.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                btSair.doClick();
            }
        });
        tbAdicionais.setEnabled(!somenteVer);
        tbAdicionaisSelecionados.setEnabled(!somenteVer);
    }

    public ConsultaAdicionais() {
        //construtor vazio necessário
    }

    public void carregaTabela() {
        List<Adicional> lista = new ArrayList<Adicional>();
        listaAdicionaisNaoInseridos.clear();
        boolean adiciona = true;
        try {
            lista = AdicionaisDAO.getInstance().findAll();

            if (listaAdicionaisInseridos.size() != 0) {
                for (Adicional listaTodosAdicionais : lista) {

                    for (Adicional listaCarregar : listaAdicionaisInseridos) {
                        if (listaCarregar.getId() == listaTodosAdicionais.getId()) {
                            adiciona = false;
                        }
                    }
                    if (adiciona) {
                        listaAdicionaisNaoInseridos.add(listaTodosAdicionais);
                    }
                    adiciona = true;
                }
            } else {
                listaAdicionaisNaoInseridos = lista;
            }

            AdicionalJtable tm = new AdicionalJtable(listaAdicionaisNaoInseridos);
            tbAdicionais.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(CrudProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void carregarTabelaAdicionaisInseridos() {
        try {
            listaAdicionaisInseridos.clear();
            List<AdicionalPedido> adicionaisPed = AdicionalPedidoDAO.getInstance().findAdicionaisDeProdutos(this.idPedido, this.idProduto);

            if (adicionaisPed.size() != 0) {
                for (AdicionalPedido adicionaisEncontrados : adicionaisPed) {
                    listaAdicionaisInseridos.add(AdicionaisDAO.getInstance().getById(adicionaisEncontrados.getAdicionalId()));
                }
            } else {
                listaAdicionaisInseridos.clear();
            }
            AdicionalJtable tm = new AdicionalJtable(listaAdicionaisInseridos);
            tbAdicionaisSelecionados.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(CrudProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAdicionais = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAdicionaisSelecionados = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        tbAdicionais.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tbAdicionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAdicionais.setName("tbConsultaProduto"); // NOI18N
        tbAdicionais.setRowHeight(18);
        jScrollPane2.setViewportView(tbAdicionais);

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 204));

        tbAdicionaisSelecionados.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tbAdicionaisSelecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAdicionaisSelecionados.setName("tbConsultaProduto"); // NOI18N
        tbAdicionaisSelecionados.setRowHeight(18);
        jScrollPane3.setViewportView(tbAdicionaisSelecionados);

        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selecionar Adicionais");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setName("lbGerenciaProj"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btAdicionar)
                .addGap(18, 18, 18)
                .addComponent(btRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 400, Short.MAX_VALUE)))
        );

        btSair.setText("Sair");
        btSair.setActionCommand("Alt");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        try {
            List<Adicional> com = new ArrayList<Adicional>();

            int[] linhas = tbAdicionais.getSelectedRows();
            for (int i = 0; i < linhas.length; i++) {

                Adicional adicional = new Adicional();
                if (listaAdicionaisInseridos.size() != 0) {
                    AdicionalJtable tm;
                    tm = new AdicionalJtable(listaAdicionaisNaoInseridos);
                    adicional = tm.get(linhas[i]);
                } else {
                    AdicionalJtable tm;
                    tm = new AdicionalJtable(null);
                    adicional = tm.get(linhas[i]);
                }
 
                RegrasGerenciamento.getInstance().salvarAdicionalPedido(adicional.getId(), this.idPedido, this.idProduto);             
                carregarTabelaAdicionaisInseridos();
                carregaTabela();
            }

        } catch (SQLException ex) {
            Logger.getLogger(ConsultaAdicionais.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        try {
            int[] linhas = tbAdicionaisSelecionados.getSelectedRows();
            for (int i = 0; i < linhas.length; i++) {

                Adicional adicional = new Adicional();
                if (listaAdicionaisInseridos.size() != 0) {
                    AdicionalJtable tm;
                    tm = new AdicionalJtable(listaAdicionaisInseridos);
                    adicional = tm.get(linhas[i]);
                } else {
                    AdicionalJtable tm;
                    tm = new AdicionalJtable(null);
                    adicional = tm.get(linhas[i]);
                }

                List<AdicionalPedido> adicionaisPed = AdicionalPedidoDAO.getInstance().findAdicionalPedidos(adicional.getId(), this.idProduto, this.idPedido);

                for (AdicionalPedido adicionaisPedido : adicionaisPed) {
                    AdicionalPedidoDAO.getInstance().remove(adicionaisPedido);
                }

                carregarTabelaAdicionaisInseridos();
                carregaTabela();

            }

        } catch (SQLException ex) {
            Logger.getLogger(ConsultaAdicionais.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAdicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAdicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAdicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAdicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAdicionais().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbAdicionais;
    private javax.swing.JTable tbAdicionaisSelecionados;
    // End of variables declaration//GEN-END:variables
}
